const uz = {
  Glavniy: "Bosh sahifa",
  tolov: "To'lov",
  muammo: "Muammo nuqtasi",
  urgench: "Urgench",
  savollar: "Ko'p so'raladigan savollar",
  qongiroq: "Qo'ng'iroqni talabi",
  katalog: "Katalog",
  qidiruv: "So‘rovni kiriting...",
  zakaz: "Buyurtmalar",
  sevimlilar: "Sevimlilar",
  savat: "Savat",
  reg: "Kirish",
  erkak: "Erkaklar",
  ayol: "Ayollar",
  sport: "Sport",
  oyin: "O'yinlar va o'yinchoqlar",
  elektr: "Elektronika",
  oshxona: "Oshxona uchun",
  sportCross: "Sport poyabzali",
  tovar: "tovarlar",
  srok: "Yetkazib berish muddati",
  brend: "Brend",
  razmer: "Hajmi",
  color: "Rangi",
  barcha: "Barchasi",
};

const ru = {
  Glavniy: "Главная",
  tolov: "Рассрочка",
  muammo: "Пункт выдачи",
  urgench: "г.Ургенч",
  savollar: "Часто задаваемые вопросы",
  qongiroq: "Заказать звонок",
  katalog: "Категории",
  qidiruv: "Введите запрос...",
  zakaz: "Мои заказы",
  sevimlilar: "Избранное",
  savat: "Корзина",
  reg: "Регистрация",
  erkak: "Мужчинам",
  ayol: "Женщинам",
  sport: "Спорт",
  oyin: "Игры и развлечения",
  elektr: "Электроника",
  oshxona: "Для кухни",
  sportCross: "Спортивные кроссовки",
  tovar: "товаров",
  srok: "Срок доставки",
  brend: "Бренд",
  razmer: "Размер",
  color: "Цвет",
  barcha: "Показать все",
};

export const languages = { uz, ru };
